# -*- coding: utf-8 -*-
"""
Created on Fri Dec 18 19:21:31 2015
@author: MohamedAbedelmalik



Each new term in the Fibonacci sequence is generated by adding the previous two 
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms.
"""

def main(limit):
    #Starts off the series 
    x = [1,2]
    
    #Creates the fibonaci series 
    while x[-1]<limit:
        x.append(x[-1]+x[-2])
    
    #Filters out on the even numbers of the series
    evenX = [i for i in x if i%2 == 0]
    
    #Adds of all the even numbers of the series together
    ans = 0
    for i in evenX:
        ans = ans + i
    
    return ans
    
print(main(4000000))